import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })
import { MongoClient } from 'mongodb';
import BranchCard from '@/components/branchCard.jsx'
export async function getServerSideProps() {
  const client = await MongoClient.connect(process.env.MONGODB_URI);
  const db = client.db('test');
  const collection = db.collection('branches');
  const branches = await collection.find().toArray();

  return {
    props: {
      branches:JSON.parse(JSON.stringify(branches)),
    },
  };
}
function createBranchCard(branch) {
  return (

    <li className="bg-blue-500  rounded-lg shadow divide-y divide-gray-200 p-4 flex items-center hover:bg-blue-700 focus:outline-none focus:bg-gray-50 transition duration-150 ease-in-out h-60 w-70">
    {/* <div
                    className="cursor-pointer"
                    onClick={(e) => {
                      e.preventDefault();
                      location.assign("/branchess/"+branch.name);
                    }}
                  > */}
  <BranchCard id={branch._id} name={branch.name}  path={branch.path}/>
  {/* </div> */}
  </li>
  );
}
export default function Home({branches}) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
        <Navbar/>
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
      <h1 className="text-center text-3xl font-bold leading-tight text-gray-900 mb-6 p-4">Branches</h1>
  <ul className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3" >
  
  {branches.map(createBranchCard)}
  </ul>
  </div>
        <Footer/>
     
    </>
  )
}





